Documentation:
    Enabled: false

Metrics/AbcSize:
  Max: 26
  Exclude:
    - lib/splitclient-rb/telemetry/memory/memory_synchronizer.rb

Metrics/MethodLength:
  Max: 20
  Exclude:
    - lib/splitclient-rb/telemetry/memory/memory_synchronizer.rb
    - lib/splitclient-rb/engine/sync_manager.rb

Metrics/ClassLength:
  Max: 150
  Exclude:
    - lib/splitclient-rb/telemetry/memory/memory_synchronizer.rb

Metrics/CyclomaticComplexity:
  Max: 11

Metrics/ParameterLists:
  Max: 8
  Exclude:
    - lib/splitclient-rb/engine/sync_manager.rb

Metrics/LineLength:
  Max: 135

Metrics/BlockLength:
  Exclude:
    - spec/**/*
    - splitclient-rb.gemspec

Naming/FileName:
  Exclude:
    - splitclient-rb.gemspec

Style/OptionalBooleanParameter:
  Exclude:
    - lib/splitclient-rb/engine/matchers/between_matcher.rb
    - lib/splitclient-rb/engine/matchers/combining_matcher.rb
    - lib/splitclient-rb/engine/matchers/equal_to_matcher.rb
    - lib/splitclient-rb/engine/matchers/less_than_or_equal_to_matcher.rb
    - lib/splitclient-rb/engine/matchers/greater_than_or_equal_to_matcher.rb

Style/HashTransformKeys:
  Exclude:
    - lib/splitclient-rb/engine/matchers/combining_matcher.rb

Style/RedundantReturn:
  Exclude:
    - lib/splitclient-rb/engine/common/impressions_manager.rb

AllCops:
  TargetRubyVersion: 2.5
  Exclude:
    - gemfiles/* # excluded as appraisal generates them with errors
    - lib/*
    - lib/murmurhash/**/*
    - lib/splitclient-rb/*
    - lib/splitclient-rb/cache/**/*
    - lib/splitclient-rb/clients/**/*
    - lib/splitclient-rb/managers/**/*
    - lib/splitclient-rb/engine/api/**/*
    - lib/splitclient-rb/engine/evaluator/**/*
    - lib/splitclient-rb/engine/metrics/**/*
    - lib/splitclient-rb/engine/models/**/*
    - lib/splitclient-rb/engine/parser/**/*
    - spec/telemetry/synchronizer_spec.rb
    - lib/splitclient-rb/engine/synchronizer.rb
    - tmp/**/*
    - lib/splitclient-rb/sse/event_source/client.rb
    - spec/**/*
    - .simplecov
