Documentation:
    Enabled: false

Metrics/MethodLength:
  Max: 15

Metrics/LineLength:
  Max: 121

Metrics/BlockLength:
  Exclude:
    - spec/**/*
    - splitclient-rb.gemspec

Naming/FileName:
  Exclude:
    - splitclient-rb.gemspec

AllCops:
  TargetRubyVersion: 2.3.6
  Exclude:
    - gemfiles/* # excluded as appraisal generates them with errors
    - lib/*
    - lib/murmurhash/**/*
    - lib/splitclient-rb/*
    - lib/splitclient-rb/cache/**/*
    - lib/splitclient-rb/clients/**/*
    - lib/splitclient-rb/managers/**/*
    - lib/splitclient-rb/engine/api/**/*
    - lib/splitclient-rb/engine/evaluator/**/*
    - lib/splitclient-rb/engine/metrics/**/*
    - lib/splitclient-rb/engine/models/**/*
    - lib/splitclient-rb/engine/parser/**/*
