pipeline:
  name: ruby-client
  identifier: rubyclient
  projectIdentifier: Harness_Split
  orgIdentifier: PROD
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: fmegithubharnessgitops
        repoName: ruby-client
        build: <+input>
        branch: harness-pipeline
        filePath: .harness/orgs/PROD/projects/Harness_Split/pipelines/rubyclient.yaml
  stages:
    - stage:
        name: Build and Test
        identifier: build_and_test
        type: CI
        spec:
          cloneCodebase: true
          caching:
            enabled: true
            override: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec:
              nestedVirtualization: true
          execution:
            steps:
              - step:
                  type: Run
                  name: Setup Ruby
                  identifier: setup_ruby
                  spec:
                    connectorRef: account.harnessImage
                    image: ruby:3.2.2-alpine
                    shell: Sh
                    command: |
                      # Install dependencies using Bundle
                      cd /harness
                      git ls-files -z
                      ls -ail
                      bundle install
                      rake compile:murmurhash
                      bundle exec rake
                  timeout: 30m
              - step:
                  type: Run
                  name: Run RuboCop
                  identifier: run_rubocop
                  spec:
                    connectorRef: account.harnessImage
                    image: ruby:3.2.2-alpine
                    shell: Sh
                    command: |
                      bundle exec rubocop
                    envVariables:
                      RUBOCOP_OPTS: "--format progress --format json --out rubocop.json"
                    outputVariables:
                      - name: RUBOCOP_RESULT
                  timeout: 10m
            rollbackSteps: []
  description: This pipeline was generated by Harness AI on 2026-02-05 18:40:52 UTC by Bilal Al-Shahwany.
