class SplitIoClient::Engine::Models::SdkInternalEvent
  SDK_READY = 'SDK_READY'
  FLAGS_UPDATED = 'FLAGS_UPDATED'
  FLAG_KILLED_NOTIFICATION = 'FLAG_KILLED_NOTIFICATION'
  SEGMENTS_UPDATED = 'SEGMENTS_UPDATED'
  RB_SEGMENTS_UPDATED = 'RB_SEGMENTS_UPDATED'
  LARGE_SEGMENTS_UPDATED = 'LARGE_SEGMENTS_UPDATED'
end
